//bio 90
//chem 45
//phy 45
window.week2Questions = [

  //bio
  {"question": "Which organelle is called the powerhouse of the cell? (Ask 2-1)", "options": ["Nucleus", "Ribosome", "Chloroplast", "Mitochondria"], "answer": "Mitochondria"},
  {"question": "Which part of the plant performs photosynthesis? (Ask 2-2)", "options": ["Chloroplast", "Nucleus", "Mitochondria", "Leaf"], "answer": "Leaf"},
  {"question": "Which pigment gives plants their green colour? (Ask 2-3)", "options": ["Nucleus", "Mitochondria", "Chloroplast", "Chlorophyll"], "answer": "Chlorophyll"},
  {"question": "What is the basic unit of life? (Ask 2-4)", "options": ["Cell", "Chloroplast", "Nucleus", "Mitochondria"], "answer": "Cell"},
  {"question": "Which tissue transports water in plants? (choose the correct option)", "options": ["Xylem", "Chloroplast", "Mitochondria", "Nucleus"], "answer": "Xylem"},
  {"question": "Which tissue transports food in plants? (choose the correct option)", "options": ["Mitochondria", "Phloem", "Chloroplast", "Nucleus"], "answer": "Phloem"},
  {"question": "Which gas is released during photosynthesis? (choose the correct option)", "options": ["Oxygen", "Chloroplast", "Mitochondria", "Nucleus"], "answer": "Oxygen"},
  {"question": "Which process do plants use to make food? (choose the correct option)", "options": ["Chloroplast", "Mitochondria", "Photosynthesis", "Nucleus"], "answer": "Photosynthesis"},
  {"question": "Which organ filters blood in humans? (choose the correct option)", "options": ["Kidney", "Nucleus", "Chloroplast", "Mitochondria"], "answer": "Kidney"},
  {"question": "What is the functional unit of the kidney? (choose the correct option)", "options": ["Nephron", "Nucleus", "Chloroplast", "Mitochondria"], "answer": "Nephron"},
  {"question": "Which part of the brain controls balance and posture? (choose the correct option)", "options": ["Mitochondria", "Cerebellum", "Nucleus", "Chloroplast"], "answer": "Cerebellum"},
  {"question": "Which gland is called the master gland? (choose the correct option)", "options": ["Chloroplast", "Mitochondria", "Pituitary gland", "Nucleus"], "answer": "Pituitary gland"},
  {"question": "Which blood cells help in clotting? (choose the correct option)", "options": ["Mitochondria", "Chloroplast", "Platelets", "Nucleus"], "answer": "Platelets"},
  {"question": "Which blood group is called the universal donor? (choose the correct option)", "options": ["Mitochondria", "O", "Chloroplast", "Nucleus"], "answer": "O"},
  {"question": "Which organ produces insulin? (choose the correct option)", "options": ["Pancreas", "Chloroplast", "Nucleus", "Mitochondria"], "answer": "Pancreas"},
  {"question": "What is the main component of plant cell wall? (choose the correct option)", "options": ["Chloroplast", "Cellulose", "Nucleus", "Mitochondria"], "answer": "Cellulose"},
  {"question": "Which structure is responsible for gaseous exchange in leaves? (choose the correct option)", "options": ["Chloroplast", "Stomata", "Nucleus", "Mitochondria"], "answer": "Stomata"},
  {"question": "Which part of neuron transmits impulses away from the cell body? (choose the correct option)", "options": ["Nucleus", "Mitochondria", "Chloroplast", "Axon"], "answer": "Axon"},
  {"question": "Which part of neuron receives impulses? (choose the correct option)", "options": ["Mitochondria", "Nucleus", "Chloroplast", "Dendrite"], "answer": "Dendrite"},
  {"question": "Which vitamin is synthesised in skin on exposure to sunlight? (choose the correct option)", "options": ["Chloroplast", "Nucleus", "Vitamin D", "Mitochondria"], "answer": "Vitamin D"},
  {"question": "Which organ is the primary site for absorption of nutrients? (choose the correct option)", "options": ["Nucleus", "Small intestine", "Mitochondria", "Chloroplast"], "answer": "Small intestine"},
  {"question": "What is the liquid portion of blood called? (choose the correct option)", "options": ["Mitochondria", "Nucleus", "Plasma", "Chloroplast"], "answer": "Plasma"},
  {"question": "Which enzyme begins the digestion of starch in the mouth? (choose the correct option)", "options": ["Nucleus", "Mitochondria", "Amylase", "Chloroplast"], "answer": "Amylase"},
  {"question": "Which organelle is the site of protein synthesis? (choose the correct option)", "options": ["Chloroplast", "Ribosome", "Mitochondria", "Nucleus"], "answer": "Ribosome"},
  {"question": "Which organisms make their own food? (choose the correct option)", "options": ["Autotrophs", "Nucleus", "Chloroplast", "Mitochondria"], "answer": "Autotrophs"},
  {"question": "Which organelle stores water in plant cells? (choose the correct option)", "options": ["Mitochondria", "Nucleus", "Chloroplast", "Vacuole"], "answer": "Vacuole"},
  {"question": "Deficiency of which vitamin causes scurvy? (choose the correct option)", "options": ["Mitochondria", "Vitamin C", "Nucleus", "Chloroplast"], "answer": "Vitamin C"},
  {"question": "Which blood vessel carries blood away from the heart? (choose the correct option)", "options": ["Chloroplast", "Mitochondria", "Arteries", "Nucleus"], "answer": "Arteries"},
  {"question": "Which hormone regulates blood glucose level? (choose the correct option)", "options": ["Insulin", "Mitochondria", "Chloroplast", "Nucleus"], "answer": "Insulin"},
  {"question": "Which organelles contain their own DNA and produce energy? (choose the correct option)", "options": ["Ribosome", "Mitochondria", "Nucleus", "Chloroplast"], "answer": "Mitochondria"},
  {"question": "Which process causes water loss from plant leaves? (choose the correct option)", "options": ["Chloroplast", "Mitochondria", "Transpiration", "Nucleus"], "answer": "Transpiration"},
  {"question": "A group of similar cells performing a function is called a — (choose the correct option)", "options": ["Chloroplast", "Tissue", "Mitochondria", "Nucleus"], "answer": "Tissue"},
  {"question": "Which blood component transports oxygen? (choose the correct option)", "options": ["Mitochondria", "Nucleus", "Chloroplast", "RBC"], "answer": "RBC"},
  {"question": "Which acid is present in the stomach? (choose the correct option)", "options": ["Hydrochloric acid", "Nucleus", "Mitochondria", "Chloroplast"], "answer": "Hydrochloric acid"},
  {"question": "Which organelle modifies and packages proteins for secretion? (choose the correct option)", "options": ["Golgi apparatus", "Chloroplast", "Nucleus", "Mitochondria"], "answer": "Golgi apparatus"},
  {"question": "Which process results in the formation of a zygote? (choose the correct option)", "options": ["Fertilization", "Chloroplast", "Nucleus", "Mitochondria"], "answer": "Fertilization"},
  {"question": "Which type of reproduction does not involve gametes? (choose the correct option)", "options": ["Chloroplast", "Mitochondria", "Nucleus", "Asexual reproduction"], "answer": "Asexual reproduction"},
  {"question": "Which organ stores and concentrates bile? (choose the correct option)", "options": ["Nucleus", "Chloroplast", "Mitochondria", "Gallbladder"], "answer": "Gallbladder"},
  {"question": "Which plant tissue transports sugars? (choose the correct option)", "options": ["Nucleus", "Chloroplast", "Phloem", "Mitochondria"], "answer": "Phloem"},
  {"question": "Which disease is caused by a virus? (choose the correct option)", "options": ["Influenza", "Nucleus", "Chloroplast", "Mitochondria"], "answer": "Influenza"},
  {"question": "Which gas is taken up by plants during photosynthesis? (choose the correct option)", "options": ["Nucleus", "Carbon dioxide", "Mitochondria", "Chloroplast"], "answer": "Carbon dioxide"},
  {"question": "Which structure is a characteristic of prokaryotes? (choose the correct option)", "options": ["Chloroplast", "Nucleoid", "Nucleus", "Mitochondria"], "answer": "Nucleoid"},
  {"question": "Which product of photosynthesis stores chemical energy? (choose the correct option)", "options": ["Glucose", "Nucleus", "Chloroplast", "Mitochondria"], "answer": "Glucose"},
  {"question": "Which organ secretes digestive enzymes into the small intestine? (choose the correct option)", "options": ["Chloroplast", "Mitochondria", "Nucleus", "Pancreas"], "answer": "Pancreas"},
  {"question": "Enzymes are primarily made of which macromolecule? (choose the correct option)", "options": ["Nucleus", "Protein", "Mitochondria", "Chloroplast"], "answer": "Protein"},
  {"question": "Which plant cell structure contains chlorophyll? (choose the correct option)", "options": ["Mitochondria", "Nucleus", "Ribosome", "Chloroplast"], "answer": "Chloroplast"},
  {"question": "Which part of the brain is responsible for higher functions? (choose the correct option)", "options": ["Mitochondria", "Cerebrum", "Nucleus", "Chloroplast"], "answer": "Cerebrum"},
  {"question": "Which organelle breaks down waste and worn-out parts? (choose the correct option)", "options": ["Nucleus", "Chloroplast", "Lysosome", "Mitochondria"], "answer": "Lysosome"},
  {"question": "Which organ helps in buoyancy in many fishes? (choose the correct option)", "options": ["Swim bladder", "Mitochondria", "Nucleus", "Chloroplast"], "answer": "Swim bladder"},
  {"question": "What are tiny openings on the leaf surface called? (choose the correct option)", "options": ["Nucleus", "Mitochondria", "Chloroplast", "Stomata"], "answer": "Stomata"},
  {"question": "Which structure in plants anchors them to the soil? (choose the correct option)", "options": ["Nucleus", "Chloroplast", "Mitochondria", "Root"], "answer": "Root"},
  {"question": "Which part of the flower receives pollen during pollination? (choose the correct option)", "options": ["Mitochondria", "Nucleus", "Stigma", "Chloroplast"], "answer": "Stigma"},
  {"question": "Which male part of flower produces pollen? (choose the correct option)", "options": ["Nucleus", "Mitochondria", "Chloroplast", "Anther"], "answer": "Anther"},
  {"question": "Which condition results from vitamin D deficiency? (choose the correct option)", "options": ["Nucleus", "Rickets", "Mitochondria", "Chloroplast"], "answer": "Rickets"},
  {"question": "The functional unit of the lung for gas exchange is? (choose the correct option)", "options": ["Mitochondria", "Nucleus", "Alveolus", "Chloroplast"], "answer": "Alveolus"},
  {"question": "What is transpiration? (choose the correct option)", "options": ["Nucleus", "Chloroplast", "Loss of water vapour from leaves", "Mitochondria"], "answer": "Loss of water vapour from leaves"},
  {"question": "What is phototropism? (choose the correct option)", "options": ["Nucleus", "Growth towards light", "Chloroplast", "Mitochondria"], "answer": "Growth towards light"},
  {"question": "What is the role of meiosis? (choose the correct option)", "options": ["Mitochondria", "Formation of gametes", "Nucleus", "Chloroplast"], "answer": "Formation of gametes"},
  {"question": "What is the role of mitosis? (choose the correct option)", "options": ["Nucleus", "Mitochondria", "Growth and repair", "Chloroplast"], "answer": "Growth and repair"},
  {"question": "What is the function of an antibody? (choose the correct option)", "options": ["Nucleus", "Chloroplast", "Mitochondria", "Neutralize pathogens"], "answer": "Neutralize pathogens"},
  {"question": "What is the primary purpose of vaccination? (choose the correct option)", "options": ["Nucleus", "Chloroplast", "Provide immunity", "Mitochondria"], "answer": "Provide immunity"},
  {"question": "Which of the following are common types of pathogens? (choose the correct option)", "options": ["Nucleus", "Chloroplast", "Mitochondria", "Bacteria, Virus, Fungi"], "answer": "Bacteria, Virus, Fungi"},
  {"question": "What does an ecosystem include? (choose the correct option)", "options": ["Nucleus", "Chloroplast", "Biotic and abiotic factors", "Mitochondria"], "answer": "Biotic and abiotic factors"},
  {"question": "What is a food chain? (choose the correct option)", "options": ["Sequence of organisms showing energy flow", "Nucleus", "Chloroplast", "Mitochondria"], "answer": "Sequence of organisms showing energy flow"},
  {"question": "What is nitrogen fixation? (choose the correct option)", "options": ["Conversion of atmospheric N2 to usable forms", "Chloroplast", "Nucleus", "Mitochondria"], "answer": "Conversion of atmospheric N2 to usable forms"},
  {"question": "Which process is a major part of the carbon cycle? (choose the correct option)", "options": ["Mitochondria", "Chloroplast", "Photosynthesis/Respiration", "Nucleus"], "answer": "Photosynthesis/Respiration"},
  {"question": "What does enzyme specificity mean? (choose the correct option)", "options": ["Nucleus", "Lock and key model", "Chloroplast", "Mitochondria"], "answer": "Lock and key model"},
  {"question": "What is a substrate in enzymatic reactions? (choose the correct option)", "options": ["Reactant for enzyme", "Chloroplast", "Nucleus", "Mitochondria"], "answer": "Reactant for enzyme"},
  {"question": "What is the role of ATP in cells? (choose the correct option)", "options": ["Energy currency", "Nucleus", "Mitochondria", "Chloroplast"], "answer": "Energy currency"},
  {"question": "Which RNAs are involved in protein synthesis? (choose the correct option)", "options": ["Nucleus", "mRNA, tRNA, rRNA", "Chloroplast", "Mitochondria"], "answer": "mRNA, tRNA, rRNA"},
  {"question": "What is a genetic mutation? (choose the correct option)", "options": ["Change in DNA sequence", "Mitochondria", "Nucleus", "Chloroplast"], "answer": "Change in DNA sequence"},
  {"question": "What does a dominant allele mean? (choose the correct option)", "options": ["Nucleus", "Mitochondria", "Expressed trait", "Chloroplast"], "answer": "Expressed trait"},
  {"question": "What does a recessive allele mean? (choose the correct option)", "options": ["Nucleus", "Chloroplast", "Mitochondria", "Expressed when dominant absent"], "answer": "Expressed when dominant absent"},
  {"question": "What is codominance? (choose the correct option)", "options": ["Chloroplast", "Both alleles expressed", "Nucleus", "Mitochondria"], "answer": "Both alleles expressed"},
  {"question": "What does natural selection refer to? (choose the correct option)", "options": ["Nucleus", "Mitochondria", "Chloroplast", "Survival of the fittest"], "answer": "Survival of the fittest"},
  {"question": "What is speciation? (choose the correct option)", "options": ["Mitochondria", "Chloroplast", "Nucleus", "Formation of new species"], "answer": "Formation of new species"},
  {"question": "What does an ecological pyramid show? (choose the correct option)", "options": ["Nucleus", "Trophic levels", "Mitochondria", "Chloroplast"], "answer": "Trophic levels"},
  {"question": "Which of these is an example of a biome? (choose the correct option)", "options": ["Nucleus", "Tropical rainforest", "Mitochondria", "Chloroplast"], "answer": "Tropical rainforest"},
  {"question": "Which factors influence population growth? (choose the correct option)", "options": ["Birth and death rates", "Chloroplast", "Nucleus", "Mitochondria"], "answer": "Birth and death rates"},
  {"question": "Which agents commonly pollinate plants? (choose the correct option)", "options": ["Mitochondria", "Chloroplast", "Insects, Wind", "Nucleus"], "answer": "Insects, Wind"},
  {"question": "Where does fertilization occur in a flower? (choose the correct option)", "options": ["Chloroplast", "Nucleus", "Ovule", "Mitochondria"], "answer": "Ovule"},
  {"question": "Which system determines sex in humans? (choose the correct option)", "options": ["XY system", "Chloroplast", "Nucleus", "Mitochondria"], "answer": "XY system"},
  {"question": "What is the function of the placenta? (choose the correct option)", "options": ["Nucleus", "Nutrient and gas exchange", "Chloroplast", "Mitochondria"], "answer": "Nutrient and gas exchange"},
  {"question": "What is homeostasis? (choose the correct option)", "options": ["Mitochondria", "Nucleus", "Chloroplast", "Maintaining internal balance"], "answer": "Maintaining internal balance"},
  {"question": "Where is DNA located in eukaryotic cells? (Ask 2-85)", "options": ["Mitochondria", "Chloroplast", "Nucleus", "Ribosome"], "answer": "Nucleus"},
  {"question": "Which organelle is called the powerhouse of the cell? (Ask 2-86)", "options": ["Nucleus", "Mitochondria", "Ribosome", "Chloroplast"], "answer": "Mitochondria"},
  {"question": "Which part of the plant performs photosynthesis? (Ask 2-87)", "options": ["Chloroplast", "Nucleus", "Leaf", "Mitochondria"], "answer": "Leaf"},
  {"question": "Which pigment gives plants their green colour? (Ask 2-88)", "options": ["Chlorophyll", "Nucleus", "Chloroplast", "Mitochondria"], "answer": "Chlorophyll"},
  {"question": "What is the basic unit of life? (Ask 2-89)", "options": ["Chloroplast", "Cell", "Nucleus", "Mitochondria"], "answer": "Cell"},
  {"question": "Which tissue transports water in plants? (Ask 2-90)", "options": ["Nucleus", "Xylem", "Chloroplast", "Mitochondria"], "answer": "Xylem"},

  //chem
  {"question": "The chemical formula of water is — (Ask 2-1)", "options": ["H2O", "CO2", "CH4", "NaCl"], "answer": "H2O"},
  {"question": "The pH of pure water is — (Ask 2-2)", "options": ["CO2", "NaCl", "7", "H2O"], "answer": "7"},
  {"question": "Which gas is used in the Haber process for ammonia synthesis? (Ask 2-3)", "options": ["CO2", "Nitrogen", "H2O", "NaCl"], "answer": "Nitrogen"},
  {"question": "Which of the following is an alkali metal? (Ask 2-4)", "options": ["CO2", "NaCl", "H2O", "Sodium"], "answer": "Sodium"},
  {"question": "Common salt is — (Ask 2-5)", "options": ["CH4", "CO2", "H2O", "NaCl"], "answer": "NaCl"},
  {"question": "HCl is — (choose the correct option)", "options": ["CO2", "NaCl", "H2O", "Acidic"], "answer": "Acidic"},
  {"question": "NaOH is — (choose the correct option)", "options": ["NaCl", "H2O", "CO2", "Base"], "answer": "Base"},
  {"question": "Which is a halogen element? (choose the correct option)", "options": ["H2O", "CO2", "Chlorine", "NaCl"], "answer": "Chlorine"},
  {"question": "The chemical symbol for gold is — (choose the correct option)", "options": ["NaCl", "H2O", "Au", "CO2"], "answer": "Au"},
  {"question": "Which gas is liberated when hydrochloric acid reacts with zinc? (choose the correct option)", "options": ["NaCl", "Hydrogen", "CO2", "H2O"], "answer": "Hydrogen"},
  {"question": "NaCl dissolves in water due to — (choose the correct option)", "options": ["Ionic bond", "CO2", "H2O", "NaCl"], "answer": "Ionic bond"},
  {"question": "Which compound is commonly used in fertilizers? (choose the correct option)", "options": ["NaCl", "H2O", "CO2", "NH3"], "answer": "NH3"},
  {"question": "Baking soda is — (choose the correct option)", "options": ["CO2", "NaCl", "NaHCO3", "H2O"], "answer": "NaHCO3"},
  {"question": "Which acid is present in vinegar? (choose the correct option)", "options": ["Acetic acid", "NaCl", "CO2", "H2O"], "answer": "Acetic acid"},
  {"question": "Which is a diatomic molecule? (choose the correct option)", "options": ["NaCl", "CO2", "H2O", "H2"], "answer": "H2"},
  {"question": "Which of these is an oxide? (choose the correct option)", "options": ["H2O", "NaCl", "CO2", "CH4"], "answer": "CO2"},
  {"question": "Which acid is present in lemon? (choose the correct option)", "options": ["Citric acid", "H2O", "NaCl", "CO2"], "answer": "Citric acid"},
  {"question": "Which element is used in thermite reaction? (choose the correct option)", "options": ["NaCl", "Aluminium", "CO2", "H2O"], "answer": "Aluminium"},
  {"question": "Which of the following is a carbohydrate? (choose the correct option)", "options": ["NaCl", "CO2", "H2O", "Glucose"], "answer": "Glucose"},
  {"question": "Which reagent is used as an oxidizing antiseptic? (choose the correct option)", "options": ["H2O", "CO2", "NaCl", "KMnO4"], "answer": "KMnO4"},
  {"question": "Which salt shows water of crystallization? (choose the correct option)", "options": ["NaCl", "CO2", "CuSO4·5H2O", "H2O"], "answer": "CuSO4·5H2O"},
  {"question": "Which gas evolves when sodium reacts with water? (choose the correct option)", "options": ["NaCl", "CO2", "H2O", "Hydrogen"], "answer": "Hydrogen"},
  {"question": "Which of these is not an element? (choose the correct option)", "options": ["NaCl", "CO2", "H2O", "Water"], "answer": "Water"},
  {"question": "The atomic number of carbon is — (choose the correct option)", "options": ["NaCl", "CO2", "6", "H2O"], "answer": "6"},
  {"question": "Which reagent is used in making soap? (choose the correct option)", "options": ["CO2", "H2O", "NaCl", "Sodium hydroxide"], "answer": "Sodium hydroxide"},
  {"question": "Which compound is commonly used as a preservative (salt)? (choose the correct option)", "options": ["H2O", "CH4", "CO2", "NaCl"], "answer": "NaCl"},
  {"question": "Which is a metalloid element? (choose the correct option)", "options": ["Boron", "H2O", "CO2", "NaCl"], "answer": "Boron"},
  {"question": "Which gas is inert in air? (choose the correct option)", "options": ["Argon", "H2O", "NaCl", "CO2"], "answer": "Argon"},
  {"question": "Which process causes rusting? (choose the correct option)", "options": ["CO2", "Oxidation", "NaCl", "H2O"], "answer": "Oxidation"},
  {"question": "What is an acid-base indicator? (choose the correct option)", "options": ["CO2", "Litmus", "H2O", "NaCl"], "answer": "Litmus"},
  {"question": "Which of these is used in making batteries? (choose the correct option)", "options": ["NaCl", "CO2", "CH4", "H2O"], "answer": "H2O"},
  {"question": "Which of these is not an element? (repeat-check) (choose the correct option)", "options": ["NaCl", "H2O", "CH4", "CO2"], "answer": "H2O"},
  {"question": "What is the formula of table sugar? (choose the correct option)", "options": ["NaCl", "CO2", "CH4", "H2O"], "answer": "H2O"},
  {"question": "Which of the following is an organic compound? (choose the correct option)", "options": ["H2O", "NaCl", "CO2", "CH4"], "answer": "H2O"},
  {"question": "Which gas is released when sodium reacts with water? (choose the correct option)", "options": ["H2O", "CH4", "NaCl", "CO2"], "answer": "H2O"},
  {"question": "Which reagent is used in extraction of metals? (choose the correct option)", "options": ["H2O", "CO2", "NaCl", "CH4"], "answer": "H2O"},
  {"question": "What is the common name of sodium bicarbonate? (choose the correct option)", "options": ["H2O", "NaCl", "CH4", "CO2"], "answer": "H2O"},
  {"question": "Which solvent is used in organic reactions commonly? (choose the correct option)", "options": ["NaCl", "CO2", "CH4", "H2O"], "answer": "H2O"},
  {"question": "Atomic number of hydrogen is — (Ask 2-39)", "options": ["NaCl", "1", "CO2", "H2O"], "answer": "1"},
  {"question": "The chemical formula of water is — (Ask 2-40)", "options": ["H2O", "NaCl", "CH4", "CO2"], "answer": "H2O"},
  {"question": "The pH of pure water is — (Ask 2-41)", "options": ["H2O", "NaCl", "CO2", "7"], "answer": "7"},
  {"question": "Which gas is used in the Haber process for ammonia synthesis? (Ask 2-42)", "options": ["NaCl", "CO2", "H2O", "Nitrogen"], "answer": "Nitrogen"},
  {"question": "Which of the following is an alkali metal? (Ask 2-43)", "options": ["H2O", "Sodium", "CO2", "NaCl"], "answer": "Sodium"},
  {"question": "Common salt is — (Ask 2-44)", "options": ["NaCl", "H2O", "CH4", "CO2"], "answer": "NaCl"},
  {"question": "HCl is — (Ask 2-45)", "options": ["CO2", "Acidic", "H2O", "NaCl"], "answer": "Acidic"},

  //phy
  {"question": "Acceleration due to gravity on Earth is approximately — (Ask 2-1)", "options": ["Joule", "Watt", "Newton", "9.8 m/s^2"], "answer": "9.8 m/s^2"},
  {"question": "Which of the following is a vector quantity? (Ask 2-2)", "options": ["Joule", "Newton", "Velocity", "Watt"], "answer": "Velocity"},
  {"question": "Speed is defined as — (Ask 2-3)", "options": ["Distance ÷ Time", "Watt", "Joule", "Newton"], "answer": "Distance ÷ Time"},
  {"question": "Velocity differs from speed because — (Ask 2-4)", "options": ["Newton", "Velocity has direction", "Watt", "Joule"], "answer": "Velocity has direction"},
  {"question": "Which law is also known as law of inertia? (Ask 2-5)", "options": ["Watt", "Newton", "Newton's first law", "Joule"], "answer": "Newton's first law"},
  {"question": "Which equation represents Newton's second law? (choose the correct option)", "options": ["Newton", "F = ma", "Watt", "Joule"], "answer": "F = ma"},
  {"question": "Which law states every action has equal and opposite reaction? (choose the correct option)", "options": ["Joule", "Watt", "Newton", "Newton's third law"], "answer": "Newton's third law"},
  {"question": "The formula for work done is — (choose the correct option)", "options": ["Joule", "Watt", "Force × Distance", "Newton"], "answer": "Force × Distance"},
  {"question": "Power is defined as — (choose the correct option)", "options": ["Joule", "Newton", "Work ÷ Time", "Watt"], "answer": "Work ÷ Time"},
  {"question": "The SI unit of energy is — (choose the correct option)", "options": ["Newton", "Pascal", "Joule", "Watt"], "answer": "Joule"},
  {"question": "Which law states pressure exerted by fluid is transmitted equally in all directions? (choose the correct option)", "options": ["Newton", "Pascal's law", "Joule", "Watt"], "answer": "Pascal's law"},
  {"question": "Which of the following is a scalar quantity? (choose the correct option)", "options": ["Speed", "Newton", "Watt", "Joule"], "answer": "Speed"},
  {"question": "Kinetic energy formula is — (choose the correct option)", "options": ["1/2 m v^2", "Newton", "Watt", "Joule"], "answer": "1/2 m v^2"},
  {"question": "Potential energy depends on — (choose the correct option)", "options": ["Mass and height", "Joule", "Newton", "Watt"], "answer": "Mass and height"},
  {"question": "The SI unit of pressure is — (choose the correct option)", "options": ["Watt", "Joule", "Pascal", "Newton"], "answer": "Pascal"},
  {"question": "Which law relates current, voltage and resistance? (choose the correct option)", "options": ["Watt", "Newton", "Joule", "Ohm's law"], "answer": "Ohm's law"},
  {"question": "Which of the following is an example of potential energy? (choose the correct option)", "options": ["Stretched spring", "Joule", "Watt", "Newton"], "answer": "Stretched spring"},
  {"question": "Kinetic energy depends on which quantities? (choose the correct option)", "options": ["Watt", "Mass and velocity", "Newton", "Joule"], "answer": "Mass and velocity"},
  {"question": "Which material is a good conductor of electricity? (choose the correct option)", "options": ["Newton", "Copper", "Joule", "Watt"], "answer": "Copper"},
  {"question": "Which of the following is an insulator? (choose the correct option)", "options": ["Watt", "Joule", "Newton", "Glass"], "answer": "Glass"},
  {"question": "Ohm's law is expressed as — (choose the correct option)", "options": ["Joule", "Newton", "V = IR", "Watt"], "answer": "V = IR"},
  {"question": "The unit of electric current is — (choose the correct option)", "options": ["Newton", "Joule", "Watt", "Ampere"], "answer": "Ampere"},
  {"question": "The unit of electric charge is — (choose the correct option)", "options": ["Watt", "Newton", "Coulomb", "Joule"], "answer": "Coulomb"},
  {"question": "Which instrument measures electric current? (choose the correct option)", "options": ["Ammeter", "Watt", "Newton", "Joule"], "answer": "Ammeter"},
  {"question": "Which of these is a magnetic material? (choose the correct option)", "options": ["Iron", "Joule", "Watt", "Newton"], "answer": "Iron"},
  {"question": "Light travels fastest in — (choose the correct option)", "options": ["Joule", "Newton", "Vacuum", "Watt"], "answer": "Vacuum"},
  {"question": "Which of these is a longitudinal wave? (choose the correct option)", "options": ["Watt", "Sound wave", "Joule", "Newton"], "answer": "Sound wave"},
  {"question": "Which of these is a transverse wave? (choose the correct option)", "options": ["Newton", "Watt", "Water wave", "Joule"], "answer": "Water wave"},
  {"question": "The slope of a velocity-time graph gives — (choose the correct option)", "options": ["Watt", "Joule", "Newton", "Acceleration"], "answer": "Acceleration"},
  {"question": "Hooke's law relates to — (choose the correct option)", "options": ["Joule", "Elastic force", "Newton", "Watt"], "answer": "Elastic force"},
  {"question": "Which of these demonstrates simple harmonic motion? (choose the correct option)", "options": ["Joule", "Pendulum", "Newton", "Watt"], "answer": "Pendulum"},
  {"question": "Frequency is measured in which unit? (choose the correct option)", "options": ["Watt", "Newton", "Joule", "Hertz"], "answer": "Hertz"},
  {"question": "What is the SI unit of wavelength? (choose the correct option)", "options": ["Newton", "Meter", "Watt", "Joule"], "answer": "Meter"},
  {"question": "What is the Doppler effect? (choose the correct option)", "options": ["Watt", "Joule", "Newton", "Change in frequency due to relative motion"], "answer": "Change in frequency due to relative motion"},
  {"question": "What is electric power formula? (choose the correct option)", "options": ["P = VI", "Joule", "Newton", "Watt"], "answer": "P = VI"},
  {"question": "What is the SI unit of capacitance? (choose the correct option)", "options": ["Watt", "Farad", "Joule", "Newton"], "answer": "Farad"},
  {"question": "Resistance of a conductor depends on which factors? (choose the correct option)", "options": ["Watt", "Newton", "Joule", "Length, area, resistivity"], "answer": "Length, area, resistivity"},
  {"question": "What is a property of series circuit? (choose the correct option)", "options": ["Watt", "Newton", "Same current", "Joule"], "answer": "Same current"},
  {"question": "What is the SI unit of force? (Ask 2-39)", "options": ["Joule", "Pascal", "Watt", "Newton"], "answer": "Newton"},
  {"question": "Acceleration due to gravity on Earth is approximately — (Ask 2-40)", "options": ["9.8 m/s^2", "Newton", "Joule", "Watt"], "answer": "9.8 m/s^2"},
  {"question": "Which of the following is a vector quantity? (Ask 2-41)", "options": ["Watt", "Velocity", "Joule", "Newton"], "answer": "Velocity"},
  {"question": "Speed is defined as — (Ask 2-42)", "options": ["Newton", "Watt", "Joule", "Distance ÷ Time"], "answer": "Distance ÷ Time"},
  {"question": "Velocity differs from speed because — (Ask 2-43)", "options": ["Newton", "Joule", "Watt", "Velocity has direction"], "answer": "Velocity has direction"},
  {"question": "Which law is also known as law of inertia? (Ask 2-44)", "options": ["Newton", "Joule", "Watt", "Newton's first law"], "answer": "Newton's first law"},
  {"question": "Which equation represents Newton's second law? (Ask 2-45)", "options": ["Joule", "Watt", "F = ma", "Newton"], "answer": "F = ma"}
];
