//bio 90
//chem 45
//phy 45
window.week1Questions = [

  //bio
  {"question": "Where is DNA located in eukaryotic cells?", "options": ["Ribosome", "Mitochondria", "Chloroplast", "Nucleus"], "answer": "Nucleus"},
  {"question": "Which organelle is called the powerhouse of the cell?", "options": ["Ribosome", "Mitochondria", "Chloroplast", "Nucleus"], "answer": "Mitochondria"},
  {"question": "Which part of the plant performs photosynthesis?", "options": ["Chloroplast", "Leaf", "Mitochondria", "Nucleus"], "answer": "Leaf"},
  {"question": "Which pigment gives plants their green colour?", "options": ["Chloroplast", "Nucleus", "Mitochondria", "Chlorophyll"], "answer": "Chlorophyll"},
  {"question": "What is the basic unit of life?", "options": ["Mitochondria", "Nucleus", "Chloroplast", "Cell"], "answer": "Cell"},
  {"question": "Which tissue transports water in plants?", "options": ["Nucleus", "Xylem", "Chloroplast", "Mitochondria"], "answer": "Xylem"},
  {"question": "Which tissue transports food in plants?", "options": ["Mitochondria", "Nucleus", "Phloem", "Chloroplast"], "answer": "Phloem"},
  {"question": "Which gas is released during photosynthesis?", "options": ["Mitochondria", "Nucleus", "Chloroplast", "Oxygen"], "answer": "Oxygen"},
  {"question": "Which process do plants use to make food?", "options": ["Mitochondria", "Chloroplast", "Nucleus", "Photosynthesis"], "answer": "Photosynthesis"},
  {"question": "Which organ filters blood in humans?", "options": ["Kidney", "Nucleus", "Mitochondria", "Chloroplast"], "answer": "Kidney"},
  {"question": "What is the functional unit of the kidney?", "options": ["Mitochondria", "Chloroplast", "Nucleus", "Nephron"], "answer": "Nephron"},
  {"question": "Which part of the brain controls balance and posture?", "options": ["Chloroplast", "Nucleus", "Cerebellum", "Mitochondria"], "answer": "Cerebellum"},
  {"question": "Which gland is called the master gland?", "options": ["Chloroplast", "Pituitary gland", "Nucleus", "Mitochondria"], "answer": "Pituitary gland"},
  {"question": "Which blood cells help in clotting?", "options": ["Nucleus", "Mitochondria", "Chloroplast", "Platelets"], "answer": "Platelets"},
  {"question": "Which blood group is called the universal donor?", "options": ["Chloroplast", "Mitochondria", "Nucleus", "O"], "answer": "O"},
  {"question": "Which organ produces insulin?", "options": ["Chloroplast", "Pancreas", "Mitochondria", "Nucleus"], "answer": "Pancreas"},
  {"question": "What is the main component of plant cell wall?", "options": ["Cellulose", "Mitochondria", "Chloroplast", "Nucleus"], "answer": "Cellulose"},
  {"question": "Which structure is responsible for gaseous exchange in leaves?", "options": ["Nucleus", "Stomata", "Mitochondria", "Chloroplast"], "answer": "Stomata"},
  {"question": "Which part of neuron transmits impulses away from the cell body?", "options": ["Mitochondria", "Axon", "Nucleus", "Chloroplast"], "answer": "Axon"},
  {"question": "Which part of neuron receives impulses?", "options": ["Mitochondria", "Dendrite", "Chloroplast", "Nucleus"], "answer": "Dendrite"},
  {"question": "Which vitamin is synthesised in skin on exposure to sunlight?", "options": ["Chloroplast", "Mitochondria", "Vitamin D", "Nucleus"], "answer": "Vitamin D"},
  {"question": "Which organ is the primary site for absorption of nutrients?", "options": ["Small intestine", "Nucleus", "Chloroplast", "Mitochondria"], "answer": "Small intestine"},
  {"question": "What is the liquid portion of blood called?", "options": ["Chloroplast", "Plasma", "Mitochondria", "Nucleus"], "answer": "Plasma"},
  {"question": "Which enzyme begins the digestion of starch in the mouth?", "options": ["Amylase", "Chloroplast", "Nucleus", "Mitochondria"], "answer": "Amylase"},
  {"question": "Which organelle is the site of protein synthesis?", "options": ["Mitochondria", "Ribosome", "Chloroplast", "Nucleus"], "answer": "Ribosome"},
  {"question": "Which organisms make their own food?", "options": ["Nucleus", "Chloroplast", "Mitochondria", "Autotrophs"], "answer": "Autotrophs"},
  {"question": "Which organelle stores water in plant cells?", "options": ["Nucleus", "Vacuole", "Mitochondria", "Chloroplast"], "answer": "Vacuole"},
  {"question": "Deficiency of which vitamin causes scurvy?", "options": ["Mitochondria", "Vitamin C", "Chloroplast", "Nucleus"], "answer": "Vitamin C"},
  {"question": "Which blood vessel carries blood away from the heart?", "options": ["Mitochondria", "Arteries", "Nucleus", "Chloroplast"], "answer": "Arteries"},
  {"question": "Which hormone regulates blood glucose level?", "options": ["Chloroplast", "Nucleus", "Insulin", "Mitochondria"], "answer": "Insulin"},
  {"question": "Which organelles contain their own DNA and produce energy?", "options": ["Chloroplast", "Ribosome", "Mitochondria", "Nucleus"], "answer": "Mitochondria"},
  {"question": "Which process causes water loss from plant leaves?", "options": ["Nucleus", "Transpiration", "Chloroplast", "Mitochondria"], "answer": "Transpiration"},
  {"question": "A group of similar cells performing a function is called a —", "options": ["Chloroplast", "Mitochondria", "Nucleus", "Tissue"], "answer": "Tissue"},
  {"question": "Which blood component transports oxygen?", "options": ["Chloroplast", "Nucleus", "RBC", "Mitochondria"], "answer": "RBC"},
  {"question": "Which acid is present in the stomach?", "options": ["Hydrochloric acid", "Chloroplast", "Nucleus", "Mitochondria"], "answer": "Hydrochloric acid"},
  {"question": "Which organelle modifies and packages proteins for secretion?", "options": ["Mitochondria", "Golgi apparatus", "Chloroplast", "Nucleus"], "answer": "Golgi apparatus"},
  {"question": "Which process results in the formation of a zygote?", "options": ["Fertilization", "Mitochondria", "Chloroplast", "Nucleus"], "answer": "Fertilization"},
  {"question": "Which type of reproduction does not involve gametes?", "options": ["Nucleus", "Asexual reproduction", "Chloroplast", "Mitochondria"], "answer": "Asexual reproduction"},
  {"question": "Which organ stores and concentrates bile?", "options": ["Mitochondria", "Nucleus", "Gallbladder", "Chloroplast"], "answer": "Gallbladder"},
  {"question": "Which plant tissue transports sugars?", "options": ["Nucleus", "Chloroplast", "Phloem", "Mitochondria"], "answer": "Phloem"},
  {"question": "Which disease is caused by a virus?", "options": ["Mitochondria", "Influenza", "Chloroplast", "Nucleus"], "answer": "Influenza"},
  {"question": "Which gas is taken up by plants during photosynthesis?", "options": ["Chloroplast", "Nucleus", "Mitochondria", "Carbon dioxide"], "answer": "Carbon dioxide"},
  {"question": "Which structure is a characteristic of prokaryotes?", "options": ["Nucleoid", "Mitochondria", "Chloroplast", "Nucleus"], "answer": "Nucleoid"},
  {"question": "Which product of photosynthesis stores chemical energy?", "options": ["Chloroplast", "Glucose", "Mitochondria", "Nucleus"], "answer": "Glucose"},
  {"question": "Which organ secretes digestive enzymes into the small intestine?", "options": ["Pancreas", "Nucleus", "Chloroplast", "Mitochondria"], "answer": "Pancreas"},
  {"question": "Enzymes are primarily made of which macromolecule?", "options": ["Protein", "Mitochondria", "Nucleus", "Chloroplast"], "answer": "Protein"},
  {"question": "Which plant cell structure contains chlorophyll?", "options": ["Ribosome", "Chloroplast", "Mitochondria", "Nucleus"], "answer": "Chloroplast"},
  {"question": "Which part of the brain is responsible for higher functions?", "options": ["Chloroplast", "Cerebrum", "Nucleus", "Mitochondria"], "answer": "Cerebrum"},
  {"question": "Which organelle breaks down waste and worn-out parts?", "options": ["Chloroplast", "Mitochondria", "Lysosome", "Nucleus"], "answer": "Lysosome"},
  {"question": "Which organ helps in buoyancy in many fishes?", "options": ["Chloroplast", "Swim bladder", "Nucleus", "Mitochondria"], "answer": "Swim bladder"},
  {"question": "What are tiny openings on the leaf surface called?", "options": ["Mitochondria", "Stomata", "Nucleus", "Chloroplast"], "answer": "Stomata"},
  {"question": "Which structure in plants anchors them to the soil?", "options": ["Mitochondria", "Nucleus", "Chloroplast", "Root"], "answer": "Root"},
  {"question": "Which part of the flower receives pollen during pollination?", "options": ["Chloroplast", "Stigma", "Mitochondria", "Nucleus"], "answer": "Stigma"},
  {"question": "Which male part of flower produces pollen?", "options": ["Mitochondria", "Chloroplast", "Nucleus", "Anther"], "answer": "Anther"},
  {"question": "Which condition results from vitamin D deficiency?", "options": ["Chloroplast", "Rickets", "Mitochondria", "Nucleus"], "answer": "Rickets"},
  {"question": "The functional unit of the lung for gas exchange is?", "options": ["Alveolus", "Mitochondria", "Chloroplast", "Nucleus"], "answer": "Alveolus"},
  {"question": "What is transpiration?", "options": ["Chloroplast", "Loss of water vapour from leaves", "Nucleus", "Mitochondria"], "answer": "Loss of water vapour from leaves"},
  {"question": "What is phototropism?", "options": ["Growth towards light", "Mitochondria", "Nucleus", "Chloroplast"], "answer": "Growth towards light"},
  {"question": "What is the role of meiosis?", "options": ["Formation of gametes", "Mitochondria", "Chloroplast", "Nucleus"], "answer": "Formation of gametes"},
  {"question": "What is the role of mitosis?", "options": ["Chloroplast", "Mitochondria", "Growth and repair", "Nucleus"], "answer": "Growth and repair"},
  {"question": "What is the function of an antibody?", "options": ["Mitochondria", "Neutralize pathogens", "Nucleus", "Chloroplast"], "answer": "Neutralize pathogens"},
  {"question": "What is the primary purpose of vaccination?", "options": ["Chloroplast", "Mitochondria", "Provide immunity", "Nucleus"], "answer": "Provide immunity"},
  {"question": "Which of the following are common types of pathogens?", "options": ["Chloroplast", "Bacteria, Virus, Fungi", "Nucleus", "Mitochondria"], "answer": "Bacteria, Virus, Fungi"},
  {"question": "What does an ecosystem include?", "options": ["Biotic and abiotic factors", "Nucleus", "Mitochondria", "Chloroplast"], "answer": "Biotic and abiotic factors"},
  {"question": "What is a food chain?", "options": ["Mitochondria", "Nucleus", "Sequence of organisms showing energy flow", "Chloroplast"], "answer": "Sequence of organisms showing energy flow"},
  {"question": "What is nitrogen fixation?", "options": ["Mitochondria", "Chloroplast", "Conversion of atmospheric N2 to usable forms", "Nucleus"], "answer": "Conversion of atmospheric N2 to usable forms"},
  {"question": "Which process is a major part of the carbon cycle?", "options": ["Photosynthesis/Respiration", "Nucleus", "Mitochondria", "Chloroplast"], "answer": "Photosynthesis/Respiration"},
  {"question": "What does enzyme specificity mean?", "options": ["Nucleus", "Chloroplast", "Mitochondria", "Lock and key model"], "answer": "Lock and key model"},
  {"question": "What is a substrate in enzymatic reactions?", "options": ["Reactant for enzyme", "Mitochondria", "Chloroplast", "Nucleus"], "answer": "Reactant for enzyme"},
  {"question": "What is the role of ATP in cells?", "options": ["Nucleus", "Mitochondria", "Chloroplast", "Energy currency"], "answer": "Energy currency"},
  {"question": "Which RNAs are involved in protein synthesis?", "options": ["Chloroplast", "Mitochondria", "mRNA, tRNA, rRNA", "Nucleus"], "answer": "mRNA, tRNA, rRNA"},
  {"question": "What is a genetic mutation?", "options": ["Chloroplast", "Change in DNA sequence", "Mitochondria", "Nucleus"], "answer": "Change in DNA sequence"},
  {"question": "What does a dominant allele mean?", "options": ["Nucleus", "Mitochondria", "Expressed trait", "Chloroplast"], "answer": "Expressed trait"},
  {"question": "What does a recessive allele mean?", "options": ["Expressed when dominant absent", "Mitochondria", "Chloroplast", "Nucleus"], "answer": "Expressed when dominant absent"},
  {"question": "What is codominance?", "options": ["Mitochondria", "Nucleus", "Chloroplast", "Both alleles expressed"], "answer": "Both alleles expressed"},
  {"question": "What does natural selection refer to?", "options": ["Survival of the fittest", "Chloroplast", "Mitochondria", "Nucleus"], "answer": "Survival of the fittest"},
  {"question": "What is speciation?", "options": ["Nucleus", "Mitochondria", "Chloroplast", "Formation of new species"], "answer": "Formation of new species"},
  {"question": "What does an ecological pyramid show?", "options": ["Trophic levels", "Mitochondria", "Chloroplast", "Nucleus"], "answer": "Trophic levels"},
  {"question": "Which of these is an example of a biome?", "options": ["Chloroplast", "Nucleus", "Tropical rainforest", "Mitochondria"], "answer": "Tropical rainforest"},
  {"question": "Which factors influence population growth?", "options": ["Nucleus", "Birth and death rates", "Chloroplast", "Mitochondria"], "answer": "Birth and death rates"},
  {"question": "Which agents commonly pollinate plants?", "options": ["Insects, Wind", "Nucleus", "Mitochondria", "Chloroplast"], "answer": "Insects, Wind"},
  {"question": "Where does fertilization occur in a flower?", "options": ["Chloroplast", "Nucleus", "Ovule", "Mitochondria"], "answer": "Ovule"},
  {"question": "Which system determines sex in humans?", "options": ["Chloroplast", "Nucleus", "Mitochondria", "XY system"], "answer": "XY system"},
  {"question": "What is the function of the placenta?", "options": ["Nucleus", "Chloroplast", "Nutrient and gas exchange", "Mitochondria"], "answer": "Nutrient and gas exchange"},
  {"question": "What is homeostasis?", "options": ["Mitochondria", "Chloroplast", "Maintaining internal balance", "Nucleus"], "answer": "Maintaining internal balance"},
  {"question": "Where is DNA located in eukaryotic cells? (choose the correct option)", "options": ["Mitochondria", "Nucleus", "Chloroplast", "Ribosome"], "answer": "Nucleus"},
  {"question": "Which organelle is called the powerhouse of the cell? (choose the correct option)", "options": ["Nucleus", "Mitochondria", "Chloroplast", "Ribosome"], "answer": "Mitochondria"},
  {"question": "Which part of the plant performs photosynthesis? (choose the correct option)", "options": ["Chloroplast", "Nucleus", "Leaf", "Mitochondria"], "answer": "Leaf"},
  {"question": "Which pigment gives plants their green colour? (choose the correct option)", "options": ["Chlorophyll", "Chloroplast", "Mitochondria", "Nucleus"], "answer": "Chlorophyll"},
  {"question": "What is the basic unit of life? (choose the correct option)", "options": ["Mitochondria", "Nucleus", "Cell", "Chloroplast"], "answer": "Cell"},

  //chem
  {"question": "Atomic number of hydrogen is —", "options": ["H2O", "CO2", "1", "NaCl"], "answer": "1"},
  {"question": "The chemical formula of water is —", "options": ["CO2", "H2O", "CH4", "NaCl"], "answer": "H2O"},
  {"question": "The pH of pure water is —", "options": ["CO2", "7", "H2O", "NaCl"], "answer": "7"},
  {"question": "Which gas is used in the Haber process for ammonia synthesis?", "options": ["CO2", "NaCl", "Nitrogen", "H2O"], "answer": "Nitrogen"},
  {"question": "Which of the following is an alkali metal?", "options": ["H2O", "NaCl", "CO2", "Sodium"], "answer": "Sodium"},
  {"question": "Common salt is —", "options": ["CO2", "NaCl", "CH4", "H2O"], "answer": "NaCl"},
  {"question": "HCl is —", "options": ["H2O", "CO2", "NaCl", "Acidic"], "answer": "Acidic"},
  {"question": "NaOH is —", "options": ["CO2", "Base", "NaCl", "H2O"], "answer": "Base"},
  {"question": "Which is a halogen element?", "options": ["NaCl", "H2O", "CO2", "Chlorine"], "answer": "Chlorine"},
  {"question": "The chemical symbol for gold is —", "options": ["Au", "CO2", "NaCl", "H2O"], "answer": "Au"},
  {"question": "Which gas is liberated when hydrochloric acid reacts with zinc?", "options": ["Hydrogen", "NaCl", "CO2", "H2O"], "answer": "Hydrogen"},
  {"question": "NaCl dissolves in water due to —", "options": ["H2O", "NaCl", "Ionic bond", "CO2"], "answer": "Ionic bond"},
  {"question": "Which compound is commonly used in fertilizers?", "options": ["H2O", "NH3", "CO2", "NaCl"], "answer": "NH3"},
  {"question": "Baking soda is —", "options": ["NaCl", "NaHCO3", "CO2", "H2O"], "answer": "NaHCO3"},
  {"question": "Which acid is present in vinegar?", "options": ["CO2", "Acetic acid", "H2O", "NaCl"], "answer": "Acetic acid"},
  {"question": "Which is a diatomic molecule?", "options": ["H2", "NaCl", "H2O", "CO2"], "answer": "H2"},
  {"question": "Which of these is an oxide?", "options": ["H2O", "CH4", "NaCl", "CO2"], "answer": "CO2"},
  {"question": "Which acid is present in lemon?", "options": ["CO2", "NaCl", "Citric acid", "H2O"], "answer": "Citric acid"},
  {"question": "Which element is used in thermite reaction?", "options": ["CO2", "NaCl", "H2O", "Aluminium"], "answer": "Aluminium"},
  {"question": "Which of the following is a carbohydrate?", "options": ["CO2", "Glucose", "NaCl", "H2O"], "answer": "Glucose"},
  {"question": "Which reagent is used as an oxidizing antiseptic?", "options": ["KMnO4", "H2O", "NaCl", "CO2"], "answer": "KMnO4"},
  {"question": "Which salt shows water of crystallization?", "options": ["H2O", "CuSO4·5H2O", "NaCl", "CO2"], "answer": "CuSO4·5H2O"},
  {"question": "Which gas evolves when sodium reacts with water?", "options": ["Hydrogen", "NaCl", "H2O", "CO2"], "answer": "Hydrogen"},
  {"question": "Which of these is not an element?", "options": ["NaCl", "CO2", "Water", "H2O"], "answer": "Water"},
  {"question": "The atomic number of carbon is —", "options": ["NaCl", "CO2", "6", "H2O"], "answer": "6"},
  {"question": "Which reagent is used in making soap?", "options": ["H2O", "CO2", "NaCl", "Sodium hydroxide"], "answer": "Sodium hydroxide"},
  {"question": "Which compound is commonly used as a preservative (salt)?", "options": ["CO2", "CH4", "H2O", "NaCl"], "answer": "NaCl"},
  {"question": "Which is a metalloid element?", "options": ["Boron", "H2O", "CO2", "NaCl"], "answer": "Boron"},
  {"question": "Which gas is inert in air?", "options": ["H2O", "CO2", "Argon", "NaCl"], "answer": "Argon"},
  {"question": "Which process causes rusting?", "options": ["H2O", "Oxidation", "NaCl", "CO2"], "answer": "Oxidation"},
  {"question": "What is an acid-base indicator?", "options": ["CO2", "Litmus", "NaCl", "H2O"], "answer": "Litmus"},
  {"question": "Which of these is used in making batteries?", "options": ["NaCl", "H2O", "CH4", "CO2"], "answer": "H2O"},
  {"question": "Which of these is not an element? (repeat-check)", "options": ["H2O", "NaCl", "CH4", "CO2"], "answer": "H2O"},
  {"question": "What is the formula of table sugar?", "options": ["NaCl", "CH4", "H2O", "CO2"], "answer": "H2O"},
  {"question": "Which of the following is an organic compound?", "options": ["CO2", "CH4", "NaCl", "H2O"], "answer": "H2O"},
  {"question": "Which gas is released when sodium reacts with water?", "options": ["CH4", "NaCl", "CO2", "H2O"], "answer": "H2O"},
  {"question": "Which reagent is used in extraction of metals?", "options": ["NaCl", "CO2", "CH4", "H2O"], "answer": "H2O"},
  {"question": "What is the common name of sodium bicarbonate?", "options": ["CH4", "NaCl", "H2O", "CO2"], "answer": "H2O"},
  {"question": "Which solvent is used in organic reactions commonly?", "options": ["H2O", "CO2", "CH4", "NaCl"], "answer": "H2O"},
  {"question": "Atomic number of hydrogen is — (choose the correct option)", "options": ["NaCl", "CO2", "H2O", "1"], "answer": "1"},
  {"question": "The chemical formula of water is — (choose the correct option)", "options": ["CH4", "CO2", "H2O", "NaCl"], "answer": "H2O"},
  {"question": "The pH of pure water is — (choose the correct option)", "options": ["H2O", "NaCl", "7", "CO2"], "answer": "7"},
  {"question": "Which gas is used in the Haber process for ammonia synthesis? (choose the correct option)", "options": ["H2O", "CO2", "Nitrogen", "NaCl"], "answer": "Nitrogen"},
  {"question": "Which of the following is an alkali metal? (choose the correct option)", "options": ["CO2", "NaCl", "H2O", "Sodium"], "answer": "Sodium"},
  {"question": "Common salt is — (choose the correct option)", "options": ["CO2", "NaCl", "H2O", "CH4"], "answer": "NaCl"},

  //phy
  {"question": "What is the SI unit of force?", "options": ["Pascal", "Newton", "Joule", "Watt"], "answer": "Newton"},
  {"question": "Acceleration due to gravity on Earth is approximately —", "options": ["Watt", "9.8 m/s^2", "Newton", "Joule"], "answer": "9.8 m/s^2"},
  {"question": "Which of the following is a vector quantity?", "options": ["Watt", "Joule", "Newton", "Velocity"], "answer": "Velocity"},
  {"question": "Speed is defined as —", "options": ["Distance ÷ Time", "Joule", "Watt", "Newton"], "answer": "Distance ÷ Time"},
  {"question": "Velocity differs from speed because —", "options": ["Newton", "Velocity has direction", "Watt", "Joule"], "answer": "Velocity has direction"},
  {"question": "Which law is also known as law of inertia?", "options": ["Joule", "Newton's first law", "Watt", "Newton"], "answer": "Newton's first law"},
  {"question": "Which equation represents Newton's second law?", "options": ["Watt", "F = ma", "Joule", "Newton"], "answer": "F = ma"},
  {"question": "Which law states every action has equal and opposite reaction?", "options": ["Watt", "Newton", "Newton's third law", "Joule"], "answer": "Newton's third law"},
  {"question": "The formula for work done is —", "options": ["Newton", "Watt", "Force × Distance", "Joule"], "answer": "Force × Distance"},
  {"question": "Power is defined as —", "options": ["Watt", "Work ÷ Time", "Newton", "Joule"], "answer": "Work ÷ Time"},
  {"question": "The SI unit of energy is —", "options": ["Watt", "Pascal", "Newton", "Joule"], "answer": "Joule"},
  {"question": "Which law states pressure exerted by fluid is transmitted equally in all directions?", "options": ["Pascal's law", "Watt", "Newton", "Joule"], "answer": "Pascal's law"},
  {"question": "Which of the following is a scalar quantity?", "options": ["Watt", "Speed", "Newton", "Joule"], "answer": "Speed"},
  {"question": "Kinetic energy formula is —", "options": ["Newton", "1/2 m v^2", "Joule", "Watt"], "answer": "1/2 m v^2"},
  {"question": "Potential energy depends on —", "options": ["Mass and height", "Joule", "Newton", "Watt"], "answer": "Mass and height"},
  {"question": "The SI unit of pressure is —", "options": ["Joule", "Newton", "Watt", "Pascal"], "answer": "Pascal"},
  {"question": "Which law relates current, voltage and resistance?", "options": ["Newton", "Ohm's law", "Watt", "Joule"], "answer": "Ohm's law"},
  {"question": "Which of the following is an example of potential energy?", "options": ["Stretched spring", "Watt", "Newton", "Joule"], "answer": "Stretched spring"},
  {"question": "Kinetic energy depends on which quantities?", "options": ["Mass and velocity", "Joule", "Watt", "Newton"], "answer": "Mass and velocity"},
  {"question": "Which material is a good conductor of electricity?", "options": ["Joule", "Copper", "Watt", "Newton"], "answer": "Copper"},
  {"question": "Which of the following is an insulator?", "options": ["Joule", "Newton", "Glass", "Watt"], "answer": "Glass"},
  {"question": "Ohm's law is expressed as —", "options": ["Watt", "V = IR", "Joule", "Newton"], "answer": "V = IR"},
  {"question": "The unit of electric current is —", "options": ["Ampere", "Newton", "Joule", "Watt"], "answer": "Ampere"},
  {"question": "The unit of electric charge is —", "options": ["Coulomb", "Newton", "Joule", "Watt"], "answer": "Coulomb"},
  {"question": "Which instrument measures electric current?", "options": ["Joule", "Ammeter", "Newton", "Watt"], "answer": "Ammeter"},
  {"question": "Which of these is a magnetic material?", "options": ["Watt", "Newton", "Joule", "Iron"], "answer": "Iron"},
  {"question": "Light travels fastest in —", "options": ["Watt", "Vacuum", "Joule", "Newton"], "answer": "Vacuum"},
  {"question": "Which of these is a longitudinal wave?", "options": ["Joule", "Watt", "Newton", "Sound wave"], "answer": "Sound wave"},
  {"question": "Which of these is a transverse wave?", "options": ["Newton", "Joule", "Watt", "Water wave"], "answer": "Water wave"},
  {"question": "The slope of a velocity-time graph gives —", "options": ["Acceleration", "Watt", "Newton", "Joule"], "answer": "Acceleration"},
  {"question": "Hooke's law relates to —", "options": ["Joule", "Newton", "Elastic force", "Watt"], "answer": "Elastic force"},
  {"question": "Which of these demonstrates simple harmonic motion?", "options": ["Newton", "Pendulum", "Joule", "Watt"], "answer": "Pendulum"},
  {"question": "Frequency is measured in which unit?", "options": ["Newton", "Joule", "Hertz", "Watt"], "answer": "Hertz"},
  {"question": "What is the SI unit of wavelength?", "options": ["Joule", "Meter", "Newton", "Watt"], "answer": "Meter"},
  {"question": "What is the Doppler effect?", "options": ["Change in frequency due to relative motion", "Newton", "Joule", "Watt"], "answer": "Change in frequency due to relative motion"},
  {"question": "What is electric power formula?", "options": ["Joule", "Watt", "Newton", "P = VI"], "answer": "P = VI"},
  {"question": "What is the SI unit of capacitance?", "options": ["Farad", "Newton", "Watt", "Joule"], "answer": "Farad"},
  {"question": "Resistance of a conductor depends on which factors?", "options": ["Joule", "Length, area, resistivity", "Newton", "Watt"], "answer": "Length, area, resistivity"},
  {"question": "What is a property of series circuit?", "options": ["Same current", "Joule", "Watt", "Newton"], "answer": "Same current"},
  {"question": "What is the SI unit of force? (choose the correct option)", "options": ["Watt", "Joule", "Newton", "Pascal"], "answer": "Newton"},
  {"question": "Acceleration due to gravity on Earth is approximately — (choose the correct option)", "options": ["Newton", "9.8 m/s^2", "Joule", "Watt"], "answer": "9.8 m/s^2"},
  {"question": "Which of the following is a vector quantity? (choose the correct option)", "options": ["Newton", "Velocity", "Joule", "Watt"], "answer": "Velocity"},
  {"question": "Speed is defined as — (choose the correct option)", "options": ["Watt", "Newton", "Joule", "Distance ÷ Time"], "answer": "Distance ÷ Time"},
  {"question": "Velocity differs from speed because — (choose the correct option)", "options": ["Velocity has direction", "Watt", "Joule", "Newton"], "answer": "Velocity has direction"},
  {"question": "Which law is also known as law of inertia? (choose the correct option)", "options": ["Newton", "Joule", "Newton's first law", "Watt"], "answer": "Newton's first law"}
];
